// LOCAL TESTING COMMAND 
### ALL CONTACTS 
GET http://localhost:3000/contacts/

### CONTACT 1 
GET http://localhost:3000/contacts/690ccd74d189441efbd05286
### CONTACT 2
GET http://localhost:3000/contacts/690ccd74d189441efbd05287

### CONTACT 3
GET http://localhost:3000/contacts/690ccd74d189441efbd05288

### CREATE NEW CONTACT (POST)
POST http://localhost:3000/contacts/
Content-Type: application/json

{
    "firstName": "Aya",
    "lastName": "Rose",
    "email": "aya.rose@example.com",
    "favoriteColor": "purple",
    "birthday": "1996-10-12"
}

### UPDATE CONTACT (PUT) - Replace with actual ID
PUT http://localhost:3000/contacts/690ccd74d189441efbd05286
Content-Type: application/json

{
    "firstName": "Aya",
    "lastName": "Rose",
    "email": "aya.rose@example.com",
    "favoriteColor": "purple",
    "birthday": "1996-10-12"
}

### DELETE CONTACT - Replace with actual ID
DELETE http://localhost:3000/contacts/690ccd74d189441efbd05288


// PRODUCTION TESTING COMMAND
### ALL CONTACTS
GET https://cse341-ks3d.onrender.com/contacts/

### CONTACT 1
GET https://cse341-ks3d.onrender.com/contacts/690ccd74d189441efbd05286

### CONTACT 2
GET https://cse341-ks3d.onrender.com/contacts/690ccd74d189441efbd05287

### CONTACT 3
GET https://cse341-ks3d.onrender.com/contacts/690ccd74d189441efbd05288

### CREATE NEW CONTACT (POST)
POST https://cse341-ks3d.onrender.com/contacts/
Content-Type: application/json

{
    "firstName": "Aya",
    "lastName": "Rose",
    "email": "aya.rose@example.com",
    "favoriteColor": "purple",
    "birthday": "1996-10-12"
}

### UPDATE CONTACT (PUT) - Replace with actual ID
PUT https://cse341-ks3d.onrender.com/contacts/690ccd74d189441efbd05286
Content-Type: application/json

{
    "firstName": "Aya",
    "lastName": "Rose",
    "email": "aya.rose@example.com",
    "favoriteColor": "purple",
    "birthday": "1996-10-12"
}

### DELETE CONTACT - Replace with actual ID
DELETE https://cse341-ks3d.onrender.com/contacts/690ccd74d189441efbd05288
